#define SHADOW_OPACITY_THRESHOLD 0.81

#define MATERIAL_FLAG_BITS 4
#define MATERIAL_FLAG_IS_OVERLAY 3
#define MATERIAL_FLAG_FLAT_NORMALS 2
#define MATERIAL_FLAG_WORLD_UVS 1
#define MATERIAL_FLAG_DISABLE_SHADOWS 0
