displayName=117 HD
internalName=117hd
compatibleVersion=1.0
author=117 HD team
description=Official 117 HD resource pack
support=https://github.com/Mark7625/resource-packs/issues
tags=Textures,Enviroments,117 HD
